FROM node:16
WORKDIR /app
COPY . .

RUN npm install -g npm@9.6.4 \
    && npm install \ 
    && npm run build:prod \ 
    && cd /usr/share/nginx/html ; mkdir pic

FROM nginx
RUN mkdir /app
COPY --from=0 /app/dist /app
COPY nginx_dev.conf /etc/nginx/nginx.conf
